//
// Created by Timur on 30.04.2020.
//

#ifndef GAME_1_VARIABLES_H
#define GAME_1_VARIABLES_H

int START_COINS_SPEED = 1;

const int WARRIOR_PRICE = 10;
int ENG_WARRIOR_HEALTH = 60;
int ENG_WARRIOR_STRENGTH = 8;
int ENG_WARRIOR_DEF_SPEED = 2;
int FR_WARRIOR_HEALTH = 50;
int FR_WARRIOR_STRENGTH = 10;
int FR_WARRIOR_DEF_SPEED = 1;

const int ARCHER_PRICE = 7;
int ENG_ARCHER_HEALTH = 30;
int ENG_ARCHER_LONG_STR = 6;
int ENG_ARCHER_SHORT_STR = 3;
int FR_ARCHER_HEALTH = 20;
int FR_ARCHER_LONG_STR = 7;
int FR_ARCHER_SHORT_STR = 4;

const int HORSEMAN_PRICE = 7;
int ENG_HORSEMAN_HEALTH = 105;
int ENG_HORSEMAN_STRENGTH = 2;
int FR_HORSEMAN_HEALTH = 90;
int FR_HORSEMAN_STRENGTH = 3;

#endif //GAME_1_VARIABLES_H
