// ENGLISH VARIABLES //
#pragma once


int ENG_WARRIOR_HEALTH = 60;
int ENG_WARRIOR_STRENGTH = 8;
int ENG_WARRIOR_DEF_SPEED = 2;

int ENG_ARCHER_HEALTH = 30;
int ENG_ARCHER_LONG_STR = 13;
int ENG_ARCHER_SHORT_STR = 13;

int ENG_HORSEMAN_HEALTH = 105;
int ENG_HORSEMAN_STRENGTH = 2;

