// FRENCH VARIABLES //
#pragma once


int FR_WARRIOR_HEALTH = 50;
int FR_WARRIOR_STRENGTH = 10;
int FR_WARRIOR_DEF_SPEED = 1;

int FR_ARCHER_HEALTH = 20;
int FR_ARCHER_LONG_STR = 15;
int FR_ARCHER_SHORT_STR = 15;

int FR_HORSEMAN_HEALTH = 90;
int FR_HORSEMAN_STRENGTH = 3;
